// @ts-check
/**
 * Build-time loader for AWS SSM Parameter Store.
 *
 * Fetches every parameter under a path prefix (e.g. `/womancart/prod/web/react/`),
 * decrypts SecureString values, and writes them to `.env.production` so that
 * `next build` inlines the `NEXT_PUBLIC_*` values into the client bundle.
 *
 * Run this BEFORE `next build` — `NEXT_PUBLIC_*` vars are compiled into the
 * bundle at build time and cannot be injected later at container runtime.
 *
 * Configuration (all via environment variables):
 *   AWS_REGION              AWS region of the parameters        (default: ap-south-1)
 *   SSM_PARAM_PATH          Path prefix to read recursively     (default: /womancart/prod/web/react/)
 *   SSM_ENV_FILE            Output env file                     (default: .env.production)
 *   SSM_REQUIRED_KEYS       Comma-separated keys that must exist (optional; build fails if missing)
 *   SSM_OPTIONAL            "true" → skip silently if no creds / no params (for local builds)
 *
 * AWS credentials are resolved by the default SDK chain:
 *   env vars (AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY [/ AWS_SESSION_TOKEN]),
 *   shared profile, or the instance / task IAM role.
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  SSMClient,
  GetParametersByPathCommand,
} from "@aws-sdk/client-ssm";

const REGION = process.env.AWS_REGION || "ap-south-1";
const PARAM_PATH = process.env.SSM_PARAM_PATH || "/womancart/prod/web/react/";
const ENV_FILE = process.env.SSM_ENV_FILE || ".env.production";
const OPTIONAL = String(process.env.SSM_OPTIONAL || "").toLowerCase() === "true";
const REQUIRED_KEYS = (process.env.SSM_REQUIRED_KEYS || "")
  .split(",")
  .map((k) => k.trim())
  .filter(Boolean);

/** Escape a value so it is safe to place after `KEY=` in a dotenv file. */
function toEnvLine(key, value) {
  const needsQuotes = /[\s#"'`$\\]|^$/.test(value);
  if (!needsQuotes) return `${key}=${value}`;
  const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  return `${key}="${escaped}"`;
}

async function fetchAllParameters() {
  const client = new SSMClient({ region: REGION });
  /** @type {Record<string, string>} */
  const params = {};
  let nextToken;

  do {
    const res = await client.send(
      new GetParametersByPathCommand({
        Path: PARAM_PATH,
        Recursive: true,
        WithDecryption: true,
        MaxResults: 10,
        NextToken: nextToken,
      }),
    );

    for (const p of res.Parameters || []) {
      if (!p.Name) continue;
      // Key = last path segment, e.g. /a/b/MY_KEY -> MY_KEY
      const key = p.Name.split("/").filter(Boolean).pop();
      if (!key) continue;
      params[key] = p.Value ?? "";
    }

    nextToken = res.NextToken;
  } while (nextToken);

  return params;
}

async function main() {
  console.log(`Loading SSM parameters from "${PARAM_PATH}" (region: ${REGION})`);

  let params;
  try {
    params = await fetchAllParameters();
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    if (OPTIONAL) {
      console.warn(
        `SSM_OPTIONAL=true — skipping SSM load (reason: ${message}).`,
      );
      return;
    }
    console.error(`Failed to load SSM parameters: ${message}`);
    process.exit(1);
  }

  const keys = Object.keys(params).sort();

  if (keys.length === 0) {
    if (OPTIONAL) {
      console.warn(
        `SSM_OPTIONAL=true — no parameters found under "${PARAM_PATH}"; continuing.`,
      );
      return;
    }
    console.error(`No parameters found under "${PARAM_PATH}".`);
    process.exit(1);
  }

  // Validate explicitly-required keys (fail fast before the build).
  const missing = REQUIRED_KEYS.filter((k) => !(k in params));
  if (missing.length > 0) {
    console.error(`Missing required SSM parameters: ${missing.join(", ")}`);
    process.exit(1);
  }

  for (const key of keys) {
    // Log the key name only — never the value.
    console.log(`Loaded: ${key}`);
  }

  const contents =
    `# Generated by scripts/load-ssm-env.mjs at ${new Date().toISOString()}\n` +
    `# Source: SSM ${PARAM_PATH} (region ${REGION}). Do NOT commit.\n` +
    keys.map((k) => toEnvLine(k, params[k])).join("\n") +
    "\n";

  const outPath = resolve(process.cwd(), ENV_FILE);
  writeFileSync(outPath, contents, { mode: 0o600 });

  console.log(`✅ SSM env loaded → ${ENV_FILE} (${keys.length} parameters)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
